AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring functions for API Gateway - GET

Parameters:
  # API Gateway
  ApiName:
    Type: String
    Description: API名  
  ApiResourcePath:
    Type: String
    Description: リソースパス  
  ApiStageName:
    Type: String
    Description: ステージ名 
  # ARN
  SNSAlertArn:
    Type: String
    Description: SNSのARN

Conditions:
  Enabled: !And [ !Not [ !Equals [ !Ref ApiName, ''] ], !Not [ !Equals [ !Ref ApiResourcePath, ''] ], !Not [ !Equals [ !Ref ApiStageName, ''] ] ]

Resources:
  AlarmApi4XXErrorAtGet:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub '*API Gateway* (${ApiName}) の ${ApiResourcePath} GET メソッドで *4XX エラー* が発生しました。'
      AlarmName: !Sub 'Notice-ApiGateway-${ApiName}-${ApiResourcePath}-4XX-Error-Occured-in-GET-Method'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiName
        - Name: Stage
          Value: !Ref ApiStageName
      EvaluationPeriods: 1
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmApi5XXErrorAtGet:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub '*API Gateway* (${ApiName}) の ${ApiResourcePath} GET メソッドで *5XX エラー* が発生しました。'
      AlarmName: !Sub 'Warning-ApiGateway-${ApiName}-${ApiResourcePath}-5XX-Error-Occured-in-GET-Method'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiName
        - Name: Stage
          Value: !Ref ApiStageName
      EvaluationPeriods: 1
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is over 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmApiLatencyAtGet:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub '*API Gateway* (${ApiName}) の ${ApiResourcePath} GET メソッドで *Latencyの値が増加* しています。'
      AlarmName: !Sub 'Warning-ApiGateway-${ApiName}-${ApiResourcePath}-Latency-in-GET-Method'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref ApiName
        - Name: Stage
          Value: !Ref ApiStageName
      EvaluationPeriods: 1
      MetricName: Latency
      Namespace: AWS/ApiGateway
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Maximum is over 2000 msec in 60 seconds.
      Period: 60
      Statistic: Maximum
      Threshold: 2000
      TreatMissingData: notBreaching