AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring functions for DynamoDB

Parameters:
  # DynamoDB
  DynamoDBEnabled:
    Type: String
    Default: Disabled
    AllowedValues:
     - Enabled
     - Disabled
  # ARN
  SNSAlertArn:
    Type: String
    Description: SNSのARN

Conditions:
  Enabled: !Equals [ !Ref DynamoDBEnabled, 'Enabled']

Resources:
  AlarmDynamoDBUserErrors:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: '*DynamoDB* で *ユーザエラー* が発生しています。'
      AlarmName: Warning-DynamoDB-UserErrors
      ComparisonOperator: GreaterThanOrEqualToThreshold
      # Not Needed
      # DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: UserErrors
      Namespace: AWS/DynamoDB
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmDynamoDBSystemErrors:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: '*DynamoDB* で *システムエラー* が発生しています。'
      AlarmName: Warning-DynamoDB-SystemErrors
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: SystemErrors
      Namespace: AWS/DynamoDB
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching