AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring functions for DynamoDB

Parameters:
  # DynamoDB
  TableName:
    Type: String
    Description: テーブル名
  # ARN
  SNSAlertArn:
    Type: String
    Description: SNSのARN

Conditions:
  Enabled: !Not [ !Equals [ !Ref TableName, ''] ]

Resources:
  AlarmDynamoDBWriteThrottleEvents:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub '*DynamoDB* (${TableName}) の書き込み処理でスロットリングが発生しています。'
      AlarmName: !Sub 'Warning-DynamoDB-${TableName}-WriteThrottleEvents'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      EvaluationPeriods: 1
      MetricName: WriteThrottleEvents
      Namespace: AWS/DynamoDB
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmDynamoDBReadThrottleEvents:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub '*DynamoDB* (${TableName}) の読み込み処理でスロットリングが発生しています。'
      AlarmName: !Sub 'Warning-DynamoDB-${TableName}-ReadThrottleEvents'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref TableName
      EvaluationPeriods: 1
      MetricName: ReadThrottleEvents
      Namespace: AWS/DynamoDB
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching