AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring functions for Kinesis

Parameters:
  # Kinesis
  KinesisStreamName:
    Type: String
    Description: Kinesis のストリーム名  
  # ARN
  SNSAlertArn:
    Type: String
    Description: SNSのARN

Conditions:
  Enabled: !Not [ !Equals [ !Ref KinesisStreamName, ''] ]

Resources:
  AlarmKinesisIteratorAgeMilliseconds:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmDescription: !Sub '*Kinesis* (${KinesisStreamName}) で *GetRecords.IteratorAgeMillisecondsの値が増加* しています。'
      AlarmName: !Sub 'Notice-Kinesis-${KinesisStreamName}-IteratorAgeMilliseconds-is-Too-Long'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 3
      Dimensions:
        - Name: StreamName
          Value: !Ref KinesisStreamName
      EvaluationPeriods: 3
      MetricName: GetRecords.IteratorAgeMilliseconds
      Namespace: AWS/Kinesis
      Period: 60
      Statistic: Maximum
      Threshold: 30000
      TreatMissingData: notBreaching
  AlarmKinesisPutRecordSuccess:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub '*Kinesis* (${KinesisStreamName}) で *入力レコード数が増加* しています。'
      AlarmName: !Sub 'Warning-Kinesis-${KinesisStreamName}-PutRecord-Success-is-Too-High'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: StreamName
          Value: !Ref KinesisStreamName
      EvaluationPeriods: 1
      MetricName: PutRecord.Success
      Namespace: AWS/Kinesis
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is over 600000 msec in 60 seconds.
      Period: 60
      Statistic: Sum
      # Number of Input Records (24000rps * 60sec)
      Threshold: 1440000
      TreatMissingData: notBreaching