AWSTemplateFormatVersion: '2010-09-09'
Description: Monitoring functions for Kinesis

Parameters:
  # Lambda
  FunctionName:
    Type: String
    Description: Lambda 関数名
  Timeout:
    Type: Number
    MinValue: 0
    Description: タイムアウト警告値 (msec)

  # ARN
  SNSAlertArn:
    Type: String
    Description: SNSのARN

Conditions:
  Enabled: !Not [ !Equals [ !Ref FunctionName, ''] ]

Resources:
  AlarmLambdaErrors:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub 'Lambda *${FunctionName}* でエラーが発生しています。'
      AlarmName: !Sub 'Warning-Lambda-${FunctionName}-Errors'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
        - Name: Resource
          Value: !Ref FunctionName
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is over 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  AlarmLambdaTimeoutWillOccur:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub 'Lambda *${FunctionName}* の実行時間がタイムアウト値に近づいています。'
      AlarmName: !Sub 'Warning-Lambda-${FunctionName}-Timeout-Will-Occur'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
        - Name: Resource
          Value: !Ref FunctionName
      EvaluationPeriods: 1
      MetricName: Duration
      Namespace: AWS/Lambda
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is over 1 count in 60 seconds.
      Period: 60
      Statistic: Maximum
      Threshold: !Ref Timeout
      TreatMissingData: notBreaching
  AlarmLambdaThrottles:
    Type: 'AWS::CloudWatch::Alarm'
    Condition: Enabled
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref SNSAlertArn
      AlarmDescription: !Sub 'Lambda *${FunctionName}* でスロットリングが発生しています。'
      AlarmName: !Sub 'Warning-Lambda-${FunctionName}-Throttles'
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref FunctionName
        - Name: Resource
          Value: !Ref FunctionName
      EvaluationPeriods: 1
      MetricName: Throttles
      Namespace: AWS/Lambda
      OKActions:
        - !Ref SNSAlertArn
      # Alert when Sum is over 1 count in 60 seconds.
      Period: 60
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching