AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationSamples/media/ivs-s3-cloudfront creates an environment for live streaming.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - Label: 
          default: 'IVS Configuration'
        Parameters: 
          - IVSAuthorized
          - IVSLatencyMode
          - IVSType
      - Label: 
          default: 'CloudFront Configuration'
        Parameters: 
          - CloudFrontDefaultTTL
          - CloudFrontMinimumTTL
          - CloudFrontMaximumTTL
          - CloudFrontOriginShield
      - Label:
          default: 'Slack Configuration'
        Parameters: 
          - SlackWorkspaceId
          - SlackChannelId
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment 
          - TagKey
          - TagValue

Parameters: 
  CloudFrontDefaultTTL:
    Default: 86400
    MinValue: 0
    Type: Number
    Description: CloudFront Default TTL [required]
  CloudFrontMinimumTTL:
    Default: 0
    MinValue: 0
    Type: Number
    Description: CloudFront Minimum TTL [required]
  CloudFrontMaximumTTL:
    Default: 31536000
    MinValue: 0
    Type: Number
    Description: CloudFront Maximum TTL [required]
  CloudFrontOriginShield:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: A flag that specifies whether Origin Shield is enabled [required]
  IVSAuthorized:
    Type: String
    AllowedValues:
      - true
      - false
    Default: false
    Description: Whether the channel is authorized [required] 
  IVSLatencyMode:
    Type: String
    AllowedValues:
      - NORMAL
      - LOW
    Default: LOW
    Description: Channel latency mode [required]
  IVSType:
    Type: String
    AllowedValues:
      - STANDARD
      - BASIC
    Default: STANDARD
    Description: The channel type [required] 
  SlackChannelId:
    Type: String
    Default: ''
    Description: Slack Channel Id for alert
  SlackWorkspaceId:
    Type: String
    Default: ''
    Description: Slack Workspace Name
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-samples 
    AllowedPattern: .+

Conditions:
  Development: !Equals [ !Ref Environment, development]

Resources:
  # Nested Stack
  IVS:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        Authorized: !Ref IVSAuthorized
        LatencyMode: !Ref IVSLatencyMode
        LogicalName: !Ref AWS::StackName
        Type: !Ref IVSType
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/ivs.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/ivs.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  StaticWebsiteHosting:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        CloudFrontDefaultTTL: !Ref CloudFrontDefaultTTL
        CloudFrontMinimumTTL: !Ref CloudFrontMinimumTTL
        CloudFrontMaximumTTL: !Ref CloudFrontMaximumTTL
        CloudFrontOriginShield: !Ref CloudFrontOriginShield
        DomainName: !Sub ivs-s3-cloudfront-${AWS::AccountId}
        Logging: DISABLED
        SNSForAlertArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        SNSForDeploymentArn: !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      TemplateURL: !If
        - Development
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/static-website-hosting-with-ssl/template.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/static-website-hosting-with-ssl/template.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  Slack:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        SlackChannelIdForAlert: !Ref SlackChannelId
        SlackWorkspaceId: !Ref SlackWorkspaceId
        SNSForAlertArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        TagEventsRule: DISABLED
      TemplateURL: !If
        - Development
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/notification/packaged.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/notification/packaged.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  SNSForAlert:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.7
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.2.7
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

Outputs:
  IngestEndpoint:
    Description: Channel ingest endpoint
    Value: !GetAtt IVS.Outputs.IngestEndpoint
  PlaybackUrl:
    Description: Channel playback URL
    Value: !GetAtt IVS.Outputs.PlaybackUrl
  StreamKey:
    Description: The stream-key value
    Value: !GetAtt IVS.Outputs.StreamKey
  CloudFrontURL:
    Description: CloudFront URL
    Value: !GetAtt StaticWebsiteHosting.Outputs.CloudFrontURL