AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationSamples/media/medialive-mediastore creates an environment for live streaming.

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label: 
          default: 'CloudFront Configuration'
        Parameters: 
          - CloudFrontDefaultTTL
          - CloudFrontMinimumTTL
          - CloudFrontMaximumTTL
          - CloudFrontViewerProtocolPolicy
          - CloudFrontRestrictViewerAccess
      - Label: 
          default: 'Live Source Configuration'
        Parameters: 
          - StreamKey
      - Label: 
          default: 'VOD Source Configuration'
        Parameters: 
          - VodSourceBucket 
      - Label: 
          default: 'MediaLive Configuration'
        Parameters: 
          - AudioBitrate 
          - AutoInputFailover
          - ChannelClass
          - FramerateDenominator
          - FramerateNumerator
          - GopNumBFrames
          - GopSize
          - H264Profile
          - H264Level
          - Height
          - VideoBitrate
          - Width
          - WhitelistRules
      - Label: 
          default: 'MediaStore Configuration'
        Parameters: 
          - ExpirationDate
          - MaxAgeSeconds
      - Label:
          default: 'MediaTailor Configuration'
        Parameters:
          - MediaTailorAdDecisionServerUrl
          - MediaTailorMaxDurationSeconds
          - MediaTailorPersonalizationThresholdSeconds
          - MediaTailorSlateAdUrl
      - Label: 
          default: 'RTMP output Configuration'
        Parameters: 
          - RtmpUrl1
          - RtmpStreamKey1
          - RtmpUrl2
          - RtmpStreamKey2
      - Label: 
          default: 'Tag Configuration'
        Parameters:
          - Environment
          - TagKey
          - TagValue

Parameters:
  AudioBitrate:
    Type: Number
    Default: 96000
    Description: Average audio bitrate in bits/second [required]
  AutoInputFailover:
    Type: String
    AllowedValues:
      - ENABLED
      - DISABLED  
    Default: ENABLED
    Description: Enable or disable automatic input failover [required]
  ChannelClass:
    Type: String
    AllowedValues:
      - STANDARD
      - SINGLE_PIPELINE  
    Default: STANDARD
    Description: Select the class of channel you intend to attach this input to [required]
  CloudFrontDefaultTTL:
    Default: 86400
    MinValue: 0
    Type: Number
    Description: CloudFront Default TTL [required]
  CloudFrontMinimumTTL:
    Default: 0
    MinValue: 0
    Type: Number
    Description: CloudFront Minimum TTL [required]
  CloudFrontMaximumTTL:
    Default: 31536000
    MinValue: 0
    Type: Number
    Description: CloudFront Maximum TTL [required]
  CloudFrontViewerProtocolPolicy:
    Type: String
    Default: redirect-to-https
    AllowedValues:
      - allow-all
      - redirect-to-https
      - https-only
    Description: CloudFront Viewer Protocol Policy [required]
  CloudFrontRestrictViewerAccess:
    Type: String
    Default: DISABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Enable or disable Restrict Viewer Access [required]  
  ExpirationDate:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 36500
    Description: The date objects to expire [required]
  FramerateDenominator:
    Type: Number
    Default: 1001
    Description: Framerate denominator [required]
  FramerateNumerator:
    Type: Number
    Default: 30000
    Description: Framerate numerator [required]  
  GopNumBFrames:
    Type: Number
    Default: 3
    Description: Number of B-frames between reference frames [required]
  GopSize:
    Type: Number
    Default: 60
    Description: GOP size (keyframe interval) in units of either frames or seconds per gopSizeUnits [required]
  H264Profile:
    Type: String
    AllowedValues:
      - BASELINE
      - HIGH
      - HIGH_10BIT
      - HIGH_422
      - HIGH_422_10BIT
      - MAIN
    Default: HIGH
    Description: H.264 Profile [required]
  H264Level:
    Type: String
    AllowedValues:
      - H264_LEVEL_1
      - H264_LEVEL_1_1
      - H264_LEVEL_1_2
      - H264_LEVEL_1_3
      - H264_LEVEL_2
      - H264_LEVEL_2_1
      - H264_LEVEL_2_2
      - H264_LEVEL_3
      - H264_LEVEL_3_1
      - H264_LEVEL_3_2
      - H264_LEVEL_4
      - H264_LEVEL_4_1
      - H264_LEVEL_4_2
      - H264_LEVEL_5
      - H264_LEVEL_5_1
      - H264_LEVEL_5_2
      - H264_LEVEL_AUTO
    Default: H264_LEVEL_4_1
    Description: H.264 Level [required]
  Height:
    Type: Number
    Default: 540
    Description: Output video height, in pixels [required]
  MaxAgeSeconds:
    Type: Number
    Default: 30000
    Description: The time in seconds that browser caches the preflight response [required]
  MediaTailorAdDecisionServerUrl:
    Type: String
    Default: ''
    Description: The URL for the ad decision server (ADS) for pre-roll ads 
  MediaTailorMaxDurationSeconds:
    Type: Number
    Default: 120
    MinValue: 0
    Description: The maximum allowed duration for the pre-roll ad avail  
  MediaTailorPersonalizationThresholdSeconds:
    Type: Number
    Default: 8
    MinValue: 0
    Description: Defines the maximum duration of underfilled ad time (in seconds) allowed in an ad break 
  MediaTailorSlateAdUrl: 
    Type: String
    Default: ''
    Description: The URL for a high-quality video asset to transcode and use to fill in time that's not used by ads. MediaTailor shows the slate to fill in gaps in media content [required]
  RtmpUrl1:
    Type: String
    Default: ''
    Description: The rtmp url a stream sends to.
  RtmpStreamKey1:
    Type: String
    Default: ''
    Description: The rtmp stream name a stream sends to.
  RtmpUrl2:
    Type: String
    Default: ''
    Description: The rtmp url a stream sends to.
  RtmpStreamKey2:
    Type: String
    Default: ''
    Description: The rtmp stream name a stream sends to.
  StreamKey:
    Type: String
    Default: stream
    Description: A unique name for the location the RTMP stream is being pushed to [required]
  VideoBitrate:
    Type: Number
    Default: 2200000
    Description: Average video bitrate in bits/second [required]
  VodSourceBucket:
    Type: String
    Default: ''
    Description: The S3 bucket Name VOD contents exist
  Width:
    Type: Number
    Default: 960
    Description: Output video width, in pixels [required]
  WhitelistRules:
    Type: String
    AllowedPattern: ^[0-9./]*$
    Default: 0.0.0.0/0
    Description: A list of one or more IPv4 CIDR addresses to allow (e.g. 0.0.0.0/0) [required]
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - production
      - test
      - development
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-samples 
    AllowedPattern: .+

Conditions:
  CreateMediaTailor: !And [ !Not [ !Equals [ !Ref MediaTailorAdDecisionServerUrl, '' ] ], !Not [ !Equals [ !Ref MediaTailorSlateAdUrl, '' ] ] ]
  Development: !Equals [ !Ref Environment, development]

Resources:
  # Nested Stack
  MediaLive:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters: 
        AdMarker: !If
          - CreateMediaTailor
          - ENABLED
          - DISABLED
        AutoInputFailover: !Ref AutoInputFailover
        AudioBitrate: !Ref AudioBitrate
        ChannelClass: !Ref ChannelClass
        FramerateDenominator: !Ref FramerateDenominator
        FramerateNumerator: !Ref FramerateNumerator
        GopNumBFrames: !Ref GopNumBFrames
        GopSize: !Ref GopSize
        H264Profile: !Ref H264Profile
        H264Level: !Ref H264Level
        Height: !Ref Height
        MediaStoreEndpoint: !Select [ 1, !Split [ "//", !GetAtt MediaStore.Outputs.Endpoint ]]
        LogicalNamePrefix: !Ref AWS::StackName
        OutputType: MEDIA_STORE
        RtmpUrl1: !Ref RtmpUrl1
        RtmpStreamKey1: !Ref RtmpStreamKey1
        RtmpUrl2: !Ref RtmpUrl2
        RtmpStreamKey2: !Ref RtmpStreamKey2
        StreamKey: !Ref StreamKey
        VideoBitrate: !Ref VideoBitrate
        VodSourceBucket: !Ref VodSourceBucket
        Width: !Ref Width
        WhitelistRules: !Ref WhitelistRules
        SNSForAlertArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        SNSForDeploymentArn: !GetAtt SNSForDeployment.Outputs.SNSTopicArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development 
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/medialive.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/medialive.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  MediaStore:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters: 
        ExpirationDate: !Ref ExpirationDate
        LogicalNamePrefix: !Ref AWS::StackName
        MaxAgeSeconds: !Ref MaxAgeSeconds
        UserAgent: !If
          - CreateMediaTailor
          - ''
          - !Ref AWS::StackName
        SNSForAlertArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        SNSForDeploymentArn: !GetAtt SNSForDeployment.Outputs.SNSTopicArn
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/mediastore.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/mediastore.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  MediaTailor:
    Condition: CreateMediaTailor
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters: 
        AdDecisionServerUrl: !Ref MediaTailorAdDecisionServerUrl
        CdnContentSegmentUrlPrefix: !Join
          - ''
          - - https://
            - !GetAtt CloudFront.Outputs.CloudFrontURL
            - '/'
            - !GetAtt MediaLive.Outputs.ManifestFile 
        LogicalNamePrefix: !Ref AWS::StackName
        MaxDurationSeconds: !Ref MediaTailorMaxDurationSeconds
        PersonalizationThresholdSeconds: !Ref MediaTailorPersonalizationThresholdSeconds
        SlateAdUrl: !Ref MediaTailorSlateAdUrl
        VideoContentSourceUrl: !Join
          - ''
          - - !GetAtt MediaStore.Outputs.Endpoint
            - '/'
            - !GetAtt MediaLive.Outputs.ManifestFile
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue        
      TemplateURL: !If
        - Development 
        - https://eijikominami-test.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/mediatailor.yaml
        - https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-templates/media/mediatailor.yaml
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        CloudFrontDefaultTTL: !Ref CloudFrontDefaultTTL
        CloudFrontMinimumTTL: !Ref CloudFrontMinimumTTL
        CloudFrontMaximumTTL: !Ref CloudFrontMaximumTTL
        CloudFrontViewerProtocolPolicy: !Ref CloudFrontViewerProtocolPolicy
        CloudFrontOriginDomainName: !Select [ 1, !Split [ "//", !GetAtt MediaStore.Outputs.Endpoint ]]
        CloudFrontOriginType: NOT_S3
        CloudFrontRestrictViewerAccess: !Ref CloudFrontRestrictViewerAccess
        Logging: DISABLED
        SNSForAlertArn: !GetAtt SNSForAlert.Outputs.SNSTopicArn
        SNSForDeploymentArn: !GetAtt SNSForDeployment.Outputs.SNSTopicArn
        UserAgent: !Ref AWS::StackName
        Environment: !Ref Environment
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      Tags:
        - Key: environment
          Value: !Ref Environment
        - Key: !Ref TagKey
          Value: !Ref TagValue
      TemplateURL: !If
        - Development
        - https://s3.amazonaws.com/eijikominami-test/aws-cloudformation-templates/edge/cloudfront.yaml
        - https://s3.amazonaws.com/eijikominami/aws-cloudformation-templates/edge/cloudfront.yaml
  SNSForAlert:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.0.63
      NotificationARNs:
        - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue
  SNSForDeployment:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 2.0.63
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        environment: !Ref Environment
        createdby: !Ref TagValue

Outputs:
  CloudFrontURL:
    Description: CloudFront URL
    Value: !Join
      - ''
      - - https://
        - !GetAtt CloudFront.Outputs.CloudFrontURL
  EndpointUrl:
    Description: Endpoint Url
    Value: !GetAtt MediaStore.Outputs.Endpoint
  MediaLiveChannelId:
    Description: MediaLive Channel Id
    Value: !GetAtt MediaLive.Outputs.ChannelId
  RtmpPrimary1:
    Description: The RTMP primary address 1
    Value: !GetAtt MediaLive.Outputs.RtmpPrimary1
  RtmpPrimary2:
    Description: The RTMP primary address 2
    Value: !GetAtt MediaLive.Outputs.RtmpPrimary2
  RtmpSecondary1:
    Description: The RTMP secondary address 1
    Value: !GetAtt MediaLive.Outputs.RtmpSecondary1
  RtmpSecondary2:
    Description: The RTMP secondary address 2
    Value: !GetAtt MediaLive.Outputs.RtmpSecondary2