AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWSCloudFormationSamples/elemental creates an environment for live streaming.

Parameters:
  AudioBitrate:
    Type: Number
    Default: 96000
    Description: Average audio bitrate in bits/second [required]
  ChannelClass:
    Type: String
    AllowedValues:
      - STANDARD
      - SINGLE_PIPELINE  
    Default: STANDARD
    Description: Select the class of channel you intend to attach this input to [required] 
  FramerateDenominator:
    Type: Number
    Default: 1001
    Description: Framerate denominator [required]
  FramerateNumerator:
    Type: Number
    Default: 30000
    Description: Framerate numerator [required]  
  GopNumBFrames:
    Type: Number
    Default: 3
    Description: Number of B-frames between reference frames [required]
  GopSize:
    Type: Number
    Default: 60
    Description: GOP size (keyframe interval) in units of either frames or seconds per gopSizeUnits [required]
  H264Profile:
    Type: String
    AllowedValues:
      - BASELINE
      - HIGH
      - HIGH_10BIT
      - HIGH_422
      - HIGH_422_10BIT
      - MAIN
    Default: HIGH
    Description: H.264 Profile [required]
  H264Level:
    Type: String
    AllowedValues:
      - H264_LEVEL_1
      - H264_LEVEL_1_1
      - H264_LEVEL_1_2
      - H264_LEVEL_1_3
      - H264_LEVEL_2
      - H264_LEVEL_2_1
      - H264_LEVEL_2_2
      - H264_LEVEL_3
      - H264_LEVEL_3_1
      - H264_LEVEL_3_2
      - H264_LEVEL_4
      - H264_LEVEL_4_1
      - H264_LEVEL_4_2
      - H264_LEVEL_5
      - H264_LEVEL_5_1
      - H264_LEVEL_5_2
      - H264_LEVEL_AUTO
    Default: H264_LEVEL_4_1
    Description: H.264 Level [required]
  Height:
    Type: Number
    Default: 540
    Description: Output video height, in pixels [required]
  StartoverWindowSeconds:
    Type: Number
    Default: 0
    Description: Maximum duration seconds of content to retain for startover playback. [required]
    MinValue: 0
  SegmentDurationSeconds:
    Type: String
    Default: 3
    Description: Duration (in seconds) of each fragment [required]
  StreamKey:
    Type: String
    Default: stream
    Description: A unique name for the location the RTMP stream is being pushed to [required]
  VideoBitrate:
    Type: Number
    Default: 2200000
    Description: Average video bitrate in bits/second [required]
  VodSourceBucket:
    Type: String
    Default: ''
    Description: The S3 bucket Name VOD contents exist
  VodDestinationBucket:
    Type: String
    Default: ''
    Description: The S3 bucket Name LIVE-to-VOD contents are stored
  Width:
    Type: Number
    Default: 960
    Description: Output video width, in pixels [required]
  WhitelistRules:
    Type: String
    AllowedPattern: ^[0-9./]*$
    Default: 0.0.0.0/0
    Description: A list of one or more IPv4 CIDR addresses to allow [required]
  SNSForAlertArn:
    Type: String
    Default: '' 
  SNSForDeploymentArn:
    Type: String
    Default: '' 
  TagKey:
    Type: String
    Default: createdby
    AllowedPattern: .+
  TagValue:
    Type: String
    Default: aws-cloudformation-samples 
    AllowedPattern: .+

Conditions:
  CreateSNSForAlert: !Equals [ !Ref SNSForAlertArn, '']
  CreateSNSForDeployment: !Equals [ !Ref SNSForDeploymentArn, '']

Resources:
  # Nested Stack
  MediaLive:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters: 
        AudioBitrate: !Ref AudioBitrate
        ChannelClass: !Ref ChannelClass
        FramerateDenominator: !Ref FramerateDenominator
        FramerateNumerator: !Ref FramerateNumerator
        GopNumBFrames: !Ref GopNumBFrames
        GopSize: !Ref GopSize
        H264Profile: !Ref H264Profile
        H264Level: !Ref H264Level
        Height: !Ref Height
        MediaPackageChannelId: !GetAtt MediaPackage.Outputs.ChannelId
        LogicalNamePrefix: !Ref AWS::StackName
        StreamKey: !Ref StreamKey
        VideoBitrate: !Ref VideoBitrate
        Width: !Ref Width
        WhitelistRules: !Ref WhitelistRules
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-samples/elemental/medialive.yaml
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
  MediaPackage:
    Type: AWS::CloudFormation::Stack
    Properties:
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters: 
        LogicalNamePrefix: !Ref AWS::StackName
        StartoverWindowSeconds: !Ref StartoverWindowSeconds
        SegmentDurationSeconds: !Ref SegmentDurationSeconds
        VodSourceBucket: !Ref VodSourceBucket
        VodDestinationBucket: !Ref VodDestinationBucket
        TagKey: !Ref TagKey
        TagValue: !Ref TagValue
      TemplateURL: https://eijikominami.s3-ap-northeast-1.amazonaws.com/aws-cloudformation-samples/elemental/mediapackage.yaml
      Tags:
        - Key: !Ref TagKey
          Value: !Ref TagValue
  SNSForAlert:
    Condition: CreateSNSForAlert
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 1.1.10
      NotificationARNs:
        - !If
          - CreateSNSForDeployment
          - !GetAtt SNSForDeployment.Outputs.SNSTopicArn
          - !Ref SNSForDeploymentArn
      Parameters:
        TopicName: !Sub Alert-createdby-${AWS::StackName}
      Tags:
        createdby: !Ref TagValue
  SNSForDeployment:
    Condition: CreateSNSForDeployment
    Type: 'AWS::Serverless::Application'
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:172664222583:applications/sns-topic
        SemanticVersion: 1.1.10
      Parameters:
        TopicName: !Sub Deployment-createdby-${AWS::StackName}
      Tags:
        createdby: !Ref TagValue

Outputs:
  EndpointUrl:
    Description: Endpoint Url
    Value: !GetAtt MediaPackage.Outputs.EndpointUrl
  MediaLiveChannelId:
    Description: MediaLive Channel Id
    Value: !GetAtt MediaLive.Outputs.ChannelId
  MediaPackageChannelId:
    Description: MediaPackage Channel Id
    Value: !GetAtt MediaPackage.Outputs.ChannelId
  Rtmp1:
    Description: The RTMP address 1
    Value: !GetAtt MediaLive.Outputs.Rtmp1
  Rtmp2:
    Description: The RTMP address 2
    Value: !GetAtt MediaLive.Outputs.Rtmp2